# ---------------- #
#   Main Configs   #
# ---------------- #
title: AceMood's Blog
tagline: Done is better than perfect
url: https://acemood.github.io
email: zmike86@gmail.com

# ---------------- #
#      Jekyll      #
# ---------------- #
permalink: /:year/:month/:day/:title/
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"

gems:
    - kramdown
    - rouge
    - jekyll-paginate

# List of links in the navigation bar
nav-links:
    Home: ""
    Archive: "archive"
    About Me: "aboutme"

# Exclude these files from production site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME