# ---------------- #
#   Main Configs   #
# ---------------- #
title: AceMood's Blog
tagline: Done is better than perfect

# ---------------- #
#      Jekyll      #
# ---------------- #
permalink: pretty
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"

gems:
    - kramdown
    - jekyll-paginate